In [5]:
from yolov5 import YOLOv5
import cv2 
from yolov5.utils.plots import colors, plot_one_box
from yolov5.utils.general import xywh2xyxy
import numpy as np
import torch

In [6]:
model_path = "~/Developer/yolov5/yolov5s.pt"
device = 'cpu'
cam = cv2.VideoCapture(0)
net = YOLOv5(model_path, device)


In [7]:
def get_detections(net, img):
    gn = torch.tensor(img.shape)[[1, 0, 1, 0]]
    detections = net.predict(img)
    for bbox in detections.xywh:
        for *xywh, cond, cls in bbox:
            if cls == 0 and cond > 0.7:
                x,y,w,h = int(xywh[0]),int(xywh[1]),int(xywh[2]),int(xywh[3])
                xyxy = xywh2xyxy(torch.tensor(xywh).unsqueeze(0))
                print(xyxy)
                label = f'{detections.names[int(cls)]} {cond:.2f}'
                plot_one_box(xyxy[0], img, label=label, color=colors(int(cls),True), line_thickness=3)
    return img

In [8]:
while True:
    ret, frame = cam.read()
    if not ret:
        break
    img = get_detections(net, frame)
    cv2.imshow("test", img)

    k = cv2.waitKey(1)
    if k%256 == 27:
        print("Escape hit, closing...")
        break
cam.release()

cv2.destroyAllWindows()

tensor([[241.10742,   5.12195, 976.96704, 713.80933]])
tensor([[239.19025,   6.72144, 974.46381, 715.99280]])
tensor([[253.75708,  20.89722, 978.37329, 720.00000]])
tensor([[256.46387,  45.52698, 965.48535, 720.00000]])
tensor([[281.60901,  53.43311, 966.80652, 720.00000]])
tensor([[287.28192,  55.89807, 959.99323, 720.00000]])
tensor([[285.24036,  57.10205, 961.72314, 720.00000]])
tensor([[283.28455,  60.31555, 958.57056, 717.59827]])
tensor([[295.24548,  62.38477, 956.69788, 719.36658]])
tensor([[305.82605,  75.07465, 949.70081, 715.79565]])
tensor([[337.27936,  98.62012, 930.72992, 713.95978]])
tensor([[350.87671, 117.18811, 924.51282, 712.26208]])
tensor([[350.43579, 126.03174, 928.68994, 711.61774]])
tensor([[349.50781, 124.28589, 929.09741, 712.44055]])
tensor([[348.23999, 121.58069, 939.38745, 710.99286]])
tensor([[349.14282, 113.98096, 929.91016, 712.39520]])
tensor([[345.50769, 114.58020, 927.29211, 713.08362]])
tensor([[343.74927, 113.10284, 930.21765, 712.33197]])
tensor([[3